# Generated by Django 4.1.13 on 2025-05-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_admin', '0002_alter_admin_information_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinical_laboratory_technician',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
