# Generated by Django 4.1.13 on 2025-05-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital_information',
            name='phone_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
