# Generated by Django 4.1.13 on 2025-05-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_alter_patient_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
